### ISSUE TITLE
401 Authorization Required

### ISSUE THREAD

**Issue by Ahmed-Soudi** [Palethorn/nas-extension#11]
401 Authorization Required on the widevine link:
https://npo-drm-gateway.samgcloud.nepworldwide.nl/authentication?custom_data=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJucG8iLCJpYXQiOjE3MDg5ODc1OTEsImxpY2Vuc2VfcHJvZmlsZSI6IndlYiIsImRybV90eXBlIjoid2lkZXZpbmUiLCJjbGllbnRfaXAiOiI3Mi4xMS4xNTcuODMifQ.xMrZkrRvY9-PYeGUq4WDxLCVxRUdyuwhKvmckDk-0yA

for the mpd in:
https://npo.nl/npo3/

Note the site needs a Dutch VPN to work.

**Comment by Ahmed-Soudi** [comment]
It suddenly worked now after a new trial! I don't know why!

**Comment by Ahmed-Soudi** [comment]
The error returned again!

**Comment by Ahmed-Soudi** [comment]
I

**Comment by Ahmed-Soudi** [comment]
I know realize that I need to keep the website page open for the authorization link to keep working in the extension. How to solve that?

**Comment by Palethorn** [comment]
Helping you resolve HTTP errors with foreign sites, especially those that require VPN, is out of the scope of this project.
