### ISSUE TITLE
New GUI hides video controls

### ISSUE THREAD

**Issue by AfterBurnerTeirusu** [Palethorn/nas-extension#4]
The new GUI bar hides the video controls on Firefox, so I cannot jump to different scenes anymore.

**Comment by Kikyoclub** [comment]
Change mode to picture-in-picture for now

**Comment by Palethorn** [comment]
Version 5.0.4 allows you to force display full controls. You can use that for now. I'll also add the option to show native player controls.

**Comment by Palethorn** [comment]
Added option to always show native video controls on Player Settings.
